plugins {
    `maven-publish`
    id("hytale-mod") version "0.+"
}

group = "com.hexvane"
version = "1.2.1"
val javaVersion = 25

repositories {
    mavenCentral()
    maven("https://maven.hytale-modding.info/releases") {
        name = "HytaleModdingReleases"
    }
    maven("https://cursemaven.com") {
        name = "CurseMaven"
    }
}

val dynamicTooltipsLib = "curse.maven:dynamictooltipslib-1459711:7939479"

dependencies {
    implementation("com.google.code.gson:gson:2.11.0")
    compileOnly(libs.jetbrains.annotations)
    compileOnly(libs.jspecify)
    compileOnly(dynamicTooltipsLib)
    runtimeOnly(dynamicTooltipsLib)
}

hytale {
    // uncomment if you want to add the Assets.zip file to your external libraries;
    // ⚠️ CAUTION, this file is very big and might make your IDE unresponsive for some time!
    //
    // addAssetsDependency = true

    // uncomment if you want to develop your mod against the pre-release version of the game.
    //
    //updateChannel = "pre-release"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }

    withSourcesJar()
}

/**
 * hstats.dev mod UUID, resolved when Gradle runs (baked into [HstatsBuildMetadata]):
 * 1. environment variable {@code AETHERHAVEN_HSTATS_MOD_UUID}
 * 2. else Gradle property {@code hstats_mod_uuid} ({@code gradle.properties} or {@code -Phstats_mod_uuid=...})
 */
val hstatsModUuid: Provider<String> =
    providers
        .environmentVariable("AETHERHAVEN_HSTATS_MOD_UUID")
        .map { it.trim() }
        .filter(String::isNotEmpty)
        .orElse(providers.gradleProperty("hstats_mod_uuid").map { it.trim() }.orElse(""))

val generateHstatsBuildMetadata =
    tasks.register("generateHstatsBuildMetadata") {
        val outDir = layout.buildDirectory.dir("generated/sources/hstats/java")
        inputs.property("hstatsModUuid", hstatsModUuid)
        outputs.dir(outDir)

        doLast {
            val uuid = hstatsModUuid.get()
            val escaped =
                uuid
                    .replace("\\", "\\\\")
                    .replace("\"", "\\\"")
            val pkgDir = outDir.get().asFile.resolve("com/hexvane/aetherhaven/generated")
            pkgDir.mkdirs()
            pkgDir.resolve("HstatsBuildMetadata.java").writeText(
                """
                package com.hexvane.aetherhaven.generated;

                /** Compile-time HStats (hstats.dev) values. Generated by Gradle — do not edit. */
                public final class HstatsBuildMetadata {
                    private HstatsBuildMetadata() {}

                    /** Mod UUID from build-time env {@code AETHERHAVEN_HSTATS_MOD_UUID} or Gradle {@code hstats_mod_uuid}; empty when unset. */
                    public static final String HSTATS_MOD_UUID = "$escaped";
                }
                """.trimIndent()
            )
        }
    }

sourceSets.named("main") {
    java.srcDir(layout.buildDirectory.dir("generated/sources/hstats/java"))
}

tasks.named<JavaCompile>("compileJava") {
    dependsOn(generateHstatsBuildMetadata)
}

tasks.named<Jar>("sourcesJar") {
    dependsOn(generateHstatsBuildMetadata)
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.addAll(listOf("-Xlint:deprecation", "-Xlint:removal", "-Xlint:unchecked"))
}

tasks.named<ProcessResources>("processResources") {
    var replaceProperties = mapOf(
        "plugin_group" to findProperty("plugin_group"),
        "plugin_maven_group" to project.group,
        "plugin_name" to project.name,
        "plugin_version" to project.version,
        "server_version" to findProperty("server_version"),

        "plugin_description" to findProperty("plugin_description"),
        "plugin_website" to findProperty("plugin_website"),

        "plugin_main_entrypoint" to findProperty("plugin_main_entrypoint"),
        "plugin_author" to findProperty("plugin_author")
    )

    filesMatching("manifest.json") {
        expand(replaceProperties)
    }

    inputs.properties(replaceProperties)
}

tasks.withType<Jar> {
    manifest {
        attributes["Specification-Title"] = rootProject.name
        attributes["Specification-Version"] = version
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] =
            providers.environmentVariable("COMMIT_SHA_SHORT")
                .map { "${version}-${it}" }
                .getOrElse(version.toString())
    }
}

publishing {
    repositories {
        // This is where you put repositories that you want to publish to.
        // Do NOT put repositories for your dependencies here.
    }

    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

val syncAssets = tasks.register<Copy>("syncAssets") {
    group = "hytale"
    description = "Automatically syncs assets from Build back to Source after server stops."

    // Take from the temporary build folder (Where the game saved changes)
    from(layout.buildDirectory.dir("resources/main"))

    // Copy into your actual project source (Where your code lives)
    into("src/main/resources")

    // IMPORTANT: Protect the manifest template from being overwritten
    exclude("manifest.json")

    // If a file exists, overwrite it with the new version from the game
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    doLast {
        println("✅ Assets successfully synced from Game to Source Code!")
    }
}

afterEvaluate {
    // Now Gradle will find it, because the plugin has finished working
    val targetTask = tasks.findByName("runServer") ?: tasks.findByName("server")

    if (targetTask != null) {
        targetTask.finalizedBy(syncAssets)
        logger.lifecycle("✅ specific task '${targetTask.name}' hooked for auto-sync.")
    } else {
        logger.warn("⚠️ Could not find 'runServer' or 'server' task to hook auto-sync into.")
    }
}
